global using System;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Data;
global using System.Diagnostics.CodeAnalysis;
global using System.Drawing;
global using System.Globalization;
global using System.Linq;
global using System.Net;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.Serialization;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading.Tasks;
global using System.Xml;
global using PurcellLibs.Common;
global using PurcellLibs.Converters;
global using PurcellLibs.Utils;
global using BooleanConverter = PurcellLibs.Converters.BooleanConverter;
global using DateTimeConverter = PurcellLibs.Converters.DateTimeConverter;
global using EnumConverter = PurcellLibs.Converters.EnumConverter;
global using GuidConverter = PurcellLibs.Converters.GuidConverter;
global using StringConverter = PurcellLibs.Converters.StringConverter;
global using TimeSpanConverter = PurcellLibs.Converters.TimeSpanConverter;
global using VersionConverter = PurcellLibs.Converters.VersionConverter;
global using PurcellLibs.Abstractions;
global using PurcellLibs.Extensions;
global using PurcellLibs.Providers;
global using PurcellLibs.Providers.Csv;
global using PurcellLibs.Providers.Excel;
global using SharpCompress.Compressors.Deflate;
global using LargeXlsx;